server:
  port: 8080

spring:
  jpa:
    database: postgresql
    show-sql: false
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:postgresql://localhost:5432/productdata
    username: postgres
    password: postgres