excel : /api/v1
health : /health
addProduct : /addProduct
addDataFromSheet : /addDataFromSheet

server:
  port: 7000
  servlet:
    context-path: /excel

spring:
  servlet:
    #specify the maximum size of excel sheet.
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  jpa:
    database: postgresql
    show-sql: false
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:postgresql://localhost:5432/productdata
    username: postgres
    password: postgres