server:
  port: 8080

spring:
  servlet:
    #specify the maximum size of excel sheet.
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  jpa:
    database: postgresql
    show-sql: false
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:postgresql://localhost:5432/productdata
    username: postgres
    password: postgres